name: Postman Tests

on:
  push:
    branches: [master]

jobs:
  postman-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node 22
        uses: actions/setup-node@v3
        with:
          node-version: 22.20.0

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Tests
        run: newman run Booking.postman_collection.json -e BookingEnv.json
